In [58]:
import numpy as np
from numpy import genfromtxt

In [123]:
X_raw = np.arange(1, 10001).reshape(-1, 1)
X = np.hstack([
    X_raw % 3,
    X_raw % 4,        # remainder when divided by 2 (this is the key!)
    X_raw % 5,       # last digit
    X_raw % 6, 
    X_raw % 7, # maybe helpful
])

In [124]:
X

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [0, 3, 3, 3, 3],
       ...,
       [2, 2, 3, 2, 2],
       [0, 3, 4, 3, 3],
       [1, 0, 0, 4, 4]], dtype=int32)

In [125]:
y= (X_raw % 2).astype(int).flatten()

In [126]:
y.shape

(10000,)

In [127]:
y

array([1, 0, 1, ..., 0, 1, 0])

In [19]:
#from sklearn.preprocessing import MinMaxScaler

In [20]:
#scaler_object = MinMaxScaler()

In [21]:
#scaler_object.fit(X)

C:\Users\RW_010\anaconda3\envs\python-cvcourse\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
#scaled_X = scaler_object.transform(X)

In [30]:
#scaled_X

In [128]:
from keras.models import Sequential
from keras.layers import Dense

In [129]:
model = Sequential()

model.add(Dense(4,input_dim=5,activation='relu'))

model.add(Dense(20,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(20,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [130]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [131]:
model.fit(X,y,epochs=100,verbose=2)

Epoch 1/100
 - 4s - loss: 0.6343 - acc: 0.6453
Epoch 2/100
 - 2s - loss: 0.4724 - acc: 0.7219
Epoch 3/100
 - 2s - loss: 0.2773 - acc: 0.8627
Epoch 4/100
 - 2s - loss: 0.1973 - acc: 0.9019
Epoch 5/100
 - 2s - loss: 0.1766 - acc: 0.9063
Epoch 6/100
 - 2s - loss: 0.1695 - acc: 0.9099
Epoch 7/100
 - 2s - loss: 0.1658 - acc: 0.9094
Epoch 8/100
 - 2s - loss: 0.1653 - acc: 0.9133
Epoch 9/100
 - 2s - loss: 0.1644 - acc: 0.9104
Epoch 10/100
 - 2s - loss: 0.1603 - acc: 0.9127
Epoch 11/100
 - 2s - loss: 0.1576 - acc: 0.9135
Epoch 12/100
 - 2s - loss: 0.1546 - acc: 0.9113
Epoch 13/100
 - 2s - loss: 0.1540 - acc: 0.9086
Epoch 14/100
 - 2s - loss: 0.1516 - acc: 0.9078
Epoch 15/100
 - 2s - loss: 0.1446 - acc: 0.9047
Epoch 16/100
 - 2s - loss: 0.1390 - acc: 0.9130
Epoch 17/100
 - 2s - loss: 0.1015 - acc: 0.9600
Epoch 18/100
 - 2s - loss: 0.0346 - acc: 0.9998
Epoch 19/100
 - 2s - loss: 0.0148 - acc: 1.0000
Epoch 20/100
 - 2s - loss: 0.0071 - acc: 1.0000
Epoch 21/100
 - 2s - loss: 0.0039 - acc: 1.0000
E

In [132]:
from sklearn.metrics import confusion_matrix,classification_report

In [133]:
# Generate numbers 1–100
X_test_raw = np.arange(20000, 23010).reshape(-1, 1)
X_test = np.hstack([
    X_test_raw % 3,
    X_test_raw % 4,        # remainder when divided by 2 (this is the key!)
    X_test_raw % 5,       # last digit
    X_test_raw % 6, 
    X_test_raw % 7, # maybe helpful
])

# Label: 0 for even, 1 for odd
y_test = (X_test_raw % 2).astype(int).flatten()

In [134]:
y_test

array([0, 1, 0, ..., 1, 0, 1])

In [135]:
predictions = model.predict_classes(X_test)
confusion_matrix(y_test,predictions)

array([[1505,    0],
       [   0, 1505]], dtype=int64)