In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [58]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [56]:
features.shape

(1372, 4)

In [8]:
X = features
y = labels

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
X.shape

(1372, 4)

In [15]:
X_train.shape

(919, 4)

In [17]:
y.shape

(1372,)

In [18]:
y_train.shape

(919,)

In [19]:
X_test.shape

(453, 4)

In [20]:
y_test.shape

(453,)

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler_object = MinMaxScaler()

In [23]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [26]:
X_test.min()

-13.2869

In [27]:
X_test.max()

17.1116

In [28]:
scaled_X_train = scaler_object.transform(X_train)

In [29]:
scaled_X_train.min()

0.0

In [31]:
scaled_X_train.max()

1.0000000000000002

In [32]:
scaled_X_test = scaler_object.transform(X_test)

In [33]:
scaled_X_test.max()

1.02679563427227

In [34]:
from keras.models import Sequential
from keras.layers import Dense

In [35]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [36]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [37]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 2s - loss: 0.6973 - acc: 0.4494
Epoch 2/50
 - 0s - loss: 0.6836 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6733 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6650 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6566 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6478 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6390 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6297 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6203 - acc: 0.5669
Epoch 10/50
 - 0s - loss: 0.6096 - acc: 0.6474
Epoch 11/50
 - 0s - loss: 0.5986 - acc: 0.6997
Epoch 12/50
 - 0s - loss: 0.5868 - acc: 0.7149
Epoch 13/50
 - 0s - loss: 0.5748 - acc: 0.7454
Epoch 14/50
 - 0s - loss: 0.5619 - acc: 0.7671
Epoch 15/50
 - 0s - loss: 0.5493 - acc: 0.7933
Epoch 16/50
 - 0s - loss: 0.5355 - acc: 0.7922
Epoch 17/50
 - 0s - loss: 0.5216 - acc: 0.8118
Epoch 18/50
 - 0s - loss: 0.5079 - acc: 0.8215
Epoch 19/50
 - 0s - loss: 0.4940 - acc: 0.8248
Epoch 20/50
 - 0s - loss: 0.4805 - acc: 0.8259
Epoch 21/50
 - 0s - loss: 0.4668 - acc: 0.8422
Epoch 22/50
 - 0s - lo

In [40]:
#model.predict_classes(scaled_X_test)

In [41]:
model.metrics_names

['loss', 'acc']

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
predictions = model.predict_classes(scaled_X_test)

In [45]:
confusion_matrix(y_test,predictions)

array([[252,   5],
       [ 22, 174]], dtype=int64)

In [48]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.92      0.98      0.95       257
        1.0       0.97      0.89      0.93       196

avg / total       0.94      0.94      0.94       453



In [49]:
model.save('mysupermodel.h5')

In [50]:
from keras.models import load_model

In [51]:
newmodel = load_model('mysupermodel.h5')

In [54]:
predictions = newmodel.predict_classes(scaled_X_test)

In [55]:
confusion_matrix(y_test,predictions)

array([[252,   5],
       [ 22, 174]], dtype=int64)